server:
  port: 8080

zuul:
  routes:
    poi_api:
      path: /api/**
      url: http://localhost:10001
      strip-prefix: true
      sensitiveHeaders:
    poi_auth:
      path: /auth/**
      url: http://localhost:10002
      strip-prefix: true
      sensitiveHeaders:
    poi_geo:
      path: /geo/**
      url: http://localhost:10003
      strip-prefix: true
      sensitiveHeaders:

oauth2:
  client:
    id: poi
    secret: poi_secret
    grantTypes: password
    scopes: read, write
    accessTokenUrl: /oauth/token
