server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:

      - id: poi_api
        uri: ${API_SERVER_URL}
        predicates:
        - Path=/api/**
        filters:
        - RewritePath=/api/, /

      - id: poi_auth
        uri: ${AUTH_SERVER_URL}
        predicates:
        - Path=/auth/**
        filters:
        - RewritePath=/auth/, /

      - id: poi_geo
        uri: ${GEO_SERVER_URL}
        predicates:
        - Path=/geo/**
        filters:
        - RewritePath=/geo/, /
