server:
  port: 8080

spring:
  data:
    elasticsearch:
      cluster-nodes: ${ES_CLUSTER_NODE}
      cluster-name: poi_geo_cluster
  cloud:
    stream:
      bindings:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

oauth2:
  jwt:
    secret: jwt_secret
