server:
  port: 8080

spring:
  data:
    mongodb:
      database: poi_auth_dev
      host: ${MONGODB_HOST}
      port: 27017
  cloud:
    stream:
      bindings:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

oauth2:
  jwt:
    secret: jwt_secret
    accessTokenAge: 360000
  client:
    id: poi
    secret: poi_secret
    grantTypes: password
    scopes: read, write

registration:
  excludedNames: 'null'
  nameMaxLength: 20
  emailPattern: "[a-z0-9!#$%&'*+\\/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+\\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?"
  passwordPattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&+=])(?=\\S+$).{8,}$"
